-- Cafe POS schema
-- 1:1  users -> user_profiles, orders -> payments
-- 1:N  categories -> products, users -> orders, orders -> order_items, products -> order_items
-- M:N  products <-> add_ons (product_add_ons)

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'CASHIER')),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- Shared primary key: a profile cannot exist without its user.
CREATE TABLE user_profiles (
    user_id   BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    full_name VARCHAR(100) NOT NULL,
    phone     VARCHAR(20),
    email     VARCHAR(100)
);

CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT         NOT NULL REFERENCES categories (id),
    name        VARCHAR(100)   NOT NULL,
    price       NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    image_url   VARCHAR(500),
    active      BOOLEAN        NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_products_category ON products (category_id);

CREATE TABLE add_ons (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(50)    NOT NULL UNIQUE,
    price  NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    active BOOLEAN        NOT NULL DEFAULT TRUE
);

CREATE TABLE product_add_ons (
    product_id BIGINT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    add_on_id  BIGINT NOT NULL REFERENCES add_ons (id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, add_on_id)
);
CREATE INDEX idx_product_add_ons_add_on ON product_add_ons (add_on_id);

CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number    VARCHAR(20)    NOT NULL UNIQUE,
    cashier_id      BIGINT         NOT NULL REFERENCES users (id),
    status          VARCHAR(20)    NOT NULL CHECK (status IN ('PENDING', 'PAID', 'CANCELLED')),
    subtotal        NUMERIC(10, 2) NOT NULL CHECK (subtotal >= 0),
    discount_amount NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total           NUMERIC(10, 2) NOT NULL CHECK (total >= 0),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_orders_cashier ON orders (cashier_id);
CREATE INDEX idx_orders_status_created ON orders (status, created_at);

-- unit_price is a snapshot: product price changes must not rewrite past orders.
CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id BIGINT         NOT NULL REFERENCES products (id),
    quantity   INT            NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0)
);
CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);

CREATE TABLE payments (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT         NOT NULL UNIQUE REFERENCES orders (id),
    method   VARCHAR(20)    NOT NULL CHECK (method IN ('CASH', 'QR_CODE', 'CARD')),
    amount   NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
    paid_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
